### ISSUE TITLE
Can we have a button to skip to the next/previous year?

### ISSUE THREAD

**Issue by ghost** [chrishulbert/datepicker#3]
Hello Chris,

I love this datepicker, can you implement 2 buttons that allow  to skip to the next/previous year?

Now when my users have to select a date in 2020, they have to click 12x5 times to get there.

Please let me know! Otherwise I may try to code this myself.

Barry

**Comment by ghost** [comment]
looking into the code, I think I can build the option, but if you can/want to do it, it's also fine by me.

**Comment by chrishulbert** [comment]
Hi,
I'm not going to find the time.

**Comment by ghost** [comment]
created a PR:
https://github.com/chrishulbert/datepicker/pull/4

**Comment by ghost** [comment]
I also have a few css patches, but you  may not like them, so I did not include them in this PR.
